"""klienci

Revision ID: 221b78eb4e8c
Revises: f64146684ede
Create Date: 2022-06-05 20:26:49.231510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221b78eb4e8c'
down_revision = 'f64146684ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('klienci',
    sa.Column('ID_Klienta', sa.Integer(), nullable=False),
    sa.Column('Imie', sa.String(length=50), nullable=False),
    sa.Column('Nazwisko', sa.String(length=50), nullable=False),
    sa.Column('Nr_Telefonu', sa.Integer(), nullable=False),
    sa.Column('ID_posiadanej_recepty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_posiadanej_recepty'], ['recepta.ID_posiadanej_recepty'], ),
    sa.PrimaryKeyConstraint('ID_Klienta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('klienci')
    # ### end Alembic commands ###
