"""produkty

Revision ID: 26698d75461c
Revises: 224f7e364ced
Create Date: 2022-06-05 20:38:16.228070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26698d75461c'
down_revision = '224f7e364ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produkty',
    sa.Column('ID_Produktu', sa.Integer(), nullable=False),
    sa.Column('Nazwa', sa.String(length=50), nullable=False),
    sa.Column('Cena', sa.Integer(), nullable=False),
    sa.Column('Data_przydatnosci', sa.Date(), nullable=False),
    sa.Column('Czy_na_recepte', sa.String(length=5), nullable=False),
    sa.Column('ID_Producenta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Producenta'], ['producent.ID_Producenta'], ),
    sa.PrimaryKeyConstraint('ID_Produktu')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produkty')
    # ### end Alembic commands ###
