"""stanowiska

Revision ID: 7de9831059e7
Revises: 26b32cf100d1
Create Date: 2022-06-05 20:19:27.677056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de9831059e7'
down_revision = '26b32cf100d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stanowiska',
    sa.Column('ID_Stanowiska', sa.Integer(), nullable=False),
    sa.Column('Nazwa_stanowiska', sa.String(length=50), nullable=False),
    sa.Column('Wynagrodzenie', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID_Stanowiska')
    )
    op.add_column('pracownicy', sa.Column('ID_Stanowiska', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pracownicy', 'stanowiska', ['ID_Stanowiska'], ['ID_Stanowiska'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pracownicy', type_='foreignkey')
    op.drop_column('pracownicy', 'ID_Stanowiska')
    op.drop_table('stanowiska')
    # ### end Alembic commands ###
