"""transakcja

Revision ID: e0ce867672d2
Revises: 26698d75461c
Create Date: 2022-06-05 20:51:55.821555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ce867672d2'
down_revision = '26698d75461c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transakcja',
    sa.Column('ID_Zakupu', sa.Integer(), nullable=False),
    sa.Column('Data_transakcji', sa.Date(), nullable=False),
    sa.Column('ID_Produktu', sa.Integer(), nullable=False),
    sa.Column('ID_Pracownika', sa.Integer(), nullable=False),
    sa.Column('ID_Klienta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Klienta'], ['klienci.ID_Klienta'], ),
    sa.ForeignKeyConstraint(['ID_Pracownika'], ['pracownicy.ID_Pracownika'], ),
    sa.ForeignKeyConstraint(['ID_Produktu'], ['produkty.ID_Produktu'], ),
    sa.PrimaryKeyConstraint('ID_Zakupu')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transakcja')
    # ### end Alembic commands ###
