"""recepta

Revision ID: f64146684ede
Revises: 7de9831059e7
Create Date: 2022-06-05 20:22:45.146878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64146684ede'
down_revision = '7de9831059e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recepta',
    sa.Column('ID_posiadanej_recepty', sa.Integer(), nullable=False),
    sa.Column('Data_waznosci_recepty', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('ID_posiadanej_recepty')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recepta')
    # ### end Alembic commands ###
