"""producent

Revision ID: 224f7e364ced
Revises: 221b78eb4e8c
Create Date: 2022-06-05 20:31:23.886288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224f7e364ced'
down_revision = '221b78eb4e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producent',
    sa.Column('ID_Producenta', sa.Integer(), nullable=False),
    sa.Column('Nazwa_producenta', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ID_Producenta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producent')
    # ### end Alembic commands ###
