"""pracownicy

Revision ID: 26b32cf100d1
Revises: 
Create Date: 2022-06-05 20:05:40.873070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b32cf100d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pracownicy',
    sa.Column('ID_Pracownika', sa.Integer(), nullable=False),
    sa.Column('Imie', sa.String(length=50), nullable=False),
    sa.Column('Nazwisko', sa.String(length=50), nullable=False),
    sa.Column('Nr_Telefonu', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID_Pracownika')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pracownicy')
    # ### end Alembic commands ###
